name = "xyzw-web-helper"
compatibility_date = "2023-12-01"

[pages_build_config]
build_command = "npm run build"
destination_dir = "dist"
name = "furina"
main = "dist/_worker.js"
compatibility_date = "2026-07-10"

[assets]
directory = "./dist"
binding = "ASSETS"
